package src.logic.card;
public enum CardValue { PLUM, MUSTARD, GREEN, SCARLET, WHITE, PEACOCK,
	KNIFE, CANDLESTICK, REVOLVER, PIPE, ROPE, WRENCH, HALL, CONSERVATORY,
	DINING_ROOM, KITCHEN, STUDY, LIBRARY, BALLROOM, LOUNGE, BILLIARD_ROOM,
 	UNKNOWN };
